[package]
name = "imagesize"
version = "0.1.1"
authors = ["Maid Dog <maiddogsrl@gmail.com>"]
description = "Quick probing of image dimensions without loading the entire file."
repository = "https://github.com/Roughsketch/imagesize"
keywords = ["image", "size"]
categories = ["multimedia", "multimedia::images"]
license = "MIT"

[dependencies]